-- =====================================================
-- 초기 샘플 데이터 (개발용)
-- 사용법: schema.sql 먼저 실행 후 이 파일 실행
--
-- ⚠ 시드 폐기: 모든 fighters / events / fighter_org_records / board_posts 시드 제거.
--   - 임의 external_id (1001-1010, 5001-5003)이 balldontlie 진짜 ID와 충돌해
--     cron sync 시 데이터 오염 발생.
--   - board_posts 더미 30건은 운영 환경에서 가짜 콘텐츠로 노출되어 신뢰도 저하.
--   - 운영 데이터는 balldontlie API 동기화 + 실사용자 게시글로만 채운다.
--   - 풀 sync: pnpm exec tsx scripts/sync-mma-full.ts
-- =====================================================
